import os
import sys
import pandas as pd

import dotenv
dotenv.load_dotenv()

# Add modules directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), 'modules'))
from modules.backtester import Backtester
from modules.ma_strategy import MovingAverageStrategy


def main():
	# Read MA signals CSV file (generated by test_ma_strategy.py)
	data_file = os.path.join(os.path.dirname(__file__), 'data', 'btc_signals.csv')
	if not os.path.exists(data_file):
		print(f"Error: MA signals file not found: {data_file}")
		print("Please run test_ma_strategy.py first to generate the signals file.")
		return
	
	df = pd.read_csv(data_file)
	df['timestamp'] = pd.to_datetime(df['timestamp'])
	
	# Generate signals if not already present
	if 'signal' not in df.columns:
		short_window = os.getenv('SHORT_WINDOW', 50)
		long_window = os.getenv('LONG_WINDOW', 200)
		strategy = MovingAverageStrategy(short_window=int(short_window), long_window=int(long_window))
		df = strategy.generate_signals(df)
	
	# Filter out rows with NaN signals
	df = df.dropna(subset=['signal'])
	
	# Run backtest
	backtester = Backtester(initial_capital=1000000)
	performance = backtester.run_backtest(df)
	
	# Add portfolio value and daily return to dataframe
	results_df = df.copy()
	results_df['portfolio_value'] = backtester.portfolio_value
	results_df['daily_return'] = results_df['portfolio_value'].pct_change() * 100
	
	# Save results to CSV file
	output_file = os.path.join(os.path.dirname(__file__), 'data', 'btc_backtest.csv')

	results_df['price'] = results_df['price'].apply(lambda x: f'{float(x):.2f}')
	results_df['short_ma'] = results_df['short_ma'].apply(lambda x: f'{float(x):.2f}')
	results_df['long_ma'] = results_df['long_ma'].apply(lambda x: f'{float(x):.2f}')
	results_df['portfolio_value'] = results_df['portfolio_value'].apply(lambda x: f'{float(x):.2f}')
	results_df['daily_return'] = results_df['daily_return'].apply(lambda x: f'{float(x):.2f}')
	results_df.to_csv(output_file, index=False)
	
	print(f'Backtest completed and saved to: {output_file}')
	print(f'\nTotal return: {performance["total_return"]:.2f}%')
	print(f'Final value: ${performance["final_value"]:,.2f}')
	print(f'Max drawdown: {performance["max_drawdown"]:.2f}%')
	print(f'\nWin rate: {performance["win_rate"]:.6f}%')


if __name__ == '__main__':
	main()
